id: ingestion-api
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: ingestion-api
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: ingestion-api
        containers:
          - name: ingestion-api
            image: samsara/ingestion-api
            cpu: 1000
            ports:
              - name: http
                containerPort: 9000
              - name: supervisord
                containerPort: 15000
            env:
              - name: TRACKING_ENABLED
                value: "false"
            volumeMounts:
              - name: logs
                mountPath: /logs
        volumes:
          - name: logs
            source:
              emptyDir: {}
    labels:
      name: ingestion-api
