id: kafka-3
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: kafka
    server: "3"
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: kafka-3
        containers:
          - name: kafka-3
            image: samsara/kafka:0.8.2.1
            ports:
              - name: kafka-port
                containerPort: 9092
            env:
              - name: KAFKA_BROKER_ID
                value: "3"
            volumeMounts:
              - name: logs
                mountPath: /logs
              - name: data
                mountPath: /data
            command:
               - "/configure-and-start.sh"
#              - "/bin/nc"
#              - "-l"
#              - "12345"
        volumes:
          - name: logs
            source:
              hostDir:
                path: /logs/kafka/3
          - name: data
            source:
              hostDir:
                path: /data/kafka/3
    labels:
      name: kafka
      server: "3"
