id: zookeeper-1
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: zookeeper
    server: "1"
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: zookeeper-1
        containers:
          - name: zookeeper-1
            image: samsara/zookeeper:3.4.6
            ports:
              - name: zookeeper-clinet-port
                containerPort: 2181
              - name: zookeeper-peer-port
                containerPort: 2888
              - name: zookeeper-election-port
                containerPort: 3888
            env:
              - name: ZK_SERVER_ID
                value: "1"
            volumeMounts:
              - name: logs
                mountPath: /opt/zookeeper/log
              - name: data
                mountPath: /opt/zookeeper/data
            command:
               - "/configure-and-start.sh"
#              - "/bin/nc"
#              - "-l"
#              - "12345"
        volumes:
          - name: logs
            source:
              emptyDir: {}
          - name: data
            source:
              hostDir:
                path: /data/zookeeper/1
    labels:
      name: zookeeper
      server: "1"
