id: qanal
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: qanal
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: qanal
        containers:
          - name: qanal
            image: samsara/qanal
            cpu: 1000
            ports:
              - name: supervisord
                containerPort: 15000
            env:
              - name: KAFKA_TOPICS_SPEC
                value: |
                  { :topic "events" :partitions :all :type :plain
                    :indexing {:strategy :simple
                               :index "events"
                               :doc-type "events"
                               :id-field "id"}}
              - name: KAFKA_PARTITIONS
                value: ":all"
              - name: TRACKING_ENABLED
                value: "true"
            volumeMounts:
              - name: logs
                mountPath: /logs
        volumes:
          - name: logs
            source:
              emptyDir: {}
    labels:
      name: qanal
